import React from 'react';
import { Modal, StyleSheet, View, Text, TouchableOpacity, ScrollView, Animated, Dimensions } from 'react-native';
import { BlurView } from 'expo-blur';
import { X, Share2, Download, Copy, Quote } from 'lucide-react-native';
import { COLORS, SPACING, BORDER_RADIUS } from '../theme';
import { EnrichedTranslationResult, Persona } from '../types';
import { Logo } from './Logo';
import { GlassCard } from './GlassCard';
import { CringeMeter } from './CringeMeter';

interface ShareModalProps {
  isVisible: boolean;
  onClose: () => void;
  result: EnrichedTranslationResult;
  persona: Persona;
  originalText: string;
}

export const ShareModal: React.FC<ShareModalProps> = ({ 
  isVisible, 
  onClose, 
  result, 
  persona,
  originalText 
}) => {
  const accentColor = persona.colorAccent || COLORS.accent;

  return (
    <Modal
      visible={isVisible}
      animationType="slide"
      transparent
      onRequestClose={onClose}
    >
      <BlurView intensity={90} tint="dark" style={StyleSheet.absoluteFill}>
        <SafeAreaView style={styles.container}>
          <View style={styles.header}>
            <Text style={styles.headerTitle}>Share the Shift</Text>
            <TouchableOpacity onPress={onClose} style={styles.closeButton}>
              <X color={COLORS.text} size={24} />
            </TouchableOpacity>
          </View>

          <ScrollView contentContainerStyle={styles.scrollContent}>
            {/* The Capture Area */}
            <View style={styles.captureArea}>
              <GlassCard style={[styles.shareCard, { borderColor: accentColor + '40' }]}>
                <View style={styles.cardHeader}>
                  <Logo size={24} showText />
                  <View style={[styles.personaTag, { backgroundColor: accentColor + '20' }]}>
                    <Text style={[styles.personaLabel, { color: accentColor }]}>{persona.label}</Text>
                  </View>
                </View>

                <View style={styles.content}>
                  <View style={styles.textSection}>
                    <Text style={styles.sectionLabel}>ORIGINAL</Text>
                    <Text style={styles.originalText}>"{originalText}"</Text>
                  </View>

                  <View style={styles.divider}>
                    <View style={[styles.line, { backgroundColor: accentColor + '30' }]} />
                    <View style={[styles.dot, { backgroundColor: accentColor }]} />
                    <View style={[styles.line, { backgroundColor: accentColor + '30' }]} />
                  </View>

                  <View style={styles.textSection}>
                    <Text style={[styles.sectionLabel, { color: accentColor }]}>SHIFTED</Text>
                    <View style={styles.quoteRow}>
                      <Quote size={20} color={accentColor + '40'} style={styles.quoteIcon} />
                      <Text style={styles.resultText}>{result.translation}</Text>
                    </View>
                  </View>
                </View>

                <View style={styles.cardFooter}>
                  <View style={styles.meterContainer}>
                    <CringeMeter score={result.cringeScore} label={result.cringeLabel} />
                  </View>
                  <Text style={styles.watermark}>Generated by Persona AI</Text>
                </View>
              </GlassCard>
            </View>

            <Text style={styles.hintText}>Screenshot this card to share the vibe! 📸</Text>

            <View style={styles.actionRow}>
              <TouchableOpacity style={styles.actionButton}>
                <Copy size={20} color={COLORS.text} />
                <Text style={styles.actionLabel}>Copy Text</Text>
              </TouchableOpacity>
              <TouchableOpacity style={[styles.actionButton, { backgroundColor: COLORS.accent }]}>
                <Share2 size={20} color={COLORS.white} />
                <Text style={[styles.actionLabel, { color: COLORS.white }]}>Share Card</Text>
              </TouchableOpacity>
            </View>
          </ScrollView>
        </SafeAreaView>
      </BlurView>
    </Modal>
  );
};

import { SafeAreaView } from 'react-native-safe-area-context';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: SPACING.lg,
  },
  headerTitle: {
    color: COLORS.text,
    fontSize: 20,
    fontWeight: '800',
  },
  closeButton: {
    padding: SPACING.xs,
  },
  scrollContent: {
    padding: SPACING.lg,
    paddingBottom: 60,
  },
  captureArea: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: SPACING.md,
  },
  shareCard: {
    width: width - SPACING.lg * 2,
    borderWidth: 2,
    padding: SPACING.xl,
    minHeight: 450,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.xl,
  },
  personaTag: {
    paddingHorizontal: SPACING.md,
    paddingVertical: 4,
    borderRadius: BORDER_RADIUS.full,
  },
  personaLabel: {
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  content: {
    flex: 1,
    gap: SPACING.lg,
  },
  textSection: {
    gap: SPACING.xs,
  },
  sectionLabel: {
    color: COLORS.textMuted,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.5,
  },
  originalText: {
    color: COLORS.textMuted,
    fontSize: 15,
    fontStyle: 'italic',
    lineHeight: 22,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginVertical: SPACING.sm,
  },
  line: {
    flex: 1,
    height: 1,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  quoteRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  quoteIcon: {
    marginTop: 4,
  },
  resultText: {
    color: COLORS.text,
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 32,
    flex: 1,
  },
  cardFooter: {
    marginTop: SPACING.xl,
    paddingTop: SPACING.lg,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
    gap: SPACING.md,
  },
  meterContainer: {
    width: '100%',
  },
  watermark: {
    textAlign: 'center',
    color: COLORS.textMuted,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 1,
    opacity: 0.5,
  },
  hintText: {
    color: COLORS.textMuted,
    textAlign: 'center',
    marginTop: SPACING.lg,
    fontSize: 13,
    fontWeight: '500',
  },
  actionRow: {
    flexDirection: 'row',
    gap: SPACING.md,
    marginTop: SPACING.xl,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    height: 56,
    borderRadius: BORDER_RADIUS.lg,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  actionLabel: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '700',
  },
});
